# Generated by Django 3.1.3 on 2020-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='summary',
        ),
        migrations.AddField(
            model_name='about',
            name='body',
            field=models.TextField(default='', max_length=500),
        ),
    ]
